
export const images = {
    logo: require("../assets/images/logo.png"),
    on1: require("../assets/images/on1.png"),
    on2: require("../assets/images/on2.png"),
    on3: require("../assets/images/on3.png"),
    blackDot: require("../assets/images/blackDot.png"),
    dot: require("../assets/images/dot.png"),
    uFindaText: require("../assets/images/dt.png"),
    add: require("../assets/images/add.png"),
    archiveAdd: require("../assets/images/archive-add.png"),
    arrowDown: require("../assets/images/arrow-down.png"),
    call: require("../assets/images/call.png"),
    chat: require("../assets/images/chat.png"),
    gallery: require("../assets/images/gallery.png"),
    greyStar: require("../assets/images/greyStar.png"),
    home: require("../assets/images/home.png"),
    menu: require("../assets/images/menu.png"),
    more: require("../assets/images/more.png"),
    bell: require("../assets/images/notification.png"),
    profileTick: require("../assets/images/profile-tick.png"),
    profile: require("../assets/images/profile.png"),
    redsave: require("../assets/images/redsave.png"),
    saved: require("../assets/images/saved.png"),
    search0: require("../assets/images/search0.png"),
    star: require("../assets/images/star.png"),
    user0: require("../assets/images/user0.png")
}
