POST http://localhost:8080/login/email
content-type: application/json

{
    "id_token": "eyJhbGciOiJIUzI1NiIsImtpZCI6IlJ4TGJEQ2Y5S2trdmp6dzAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3RncHN0c2NxdGt2bmlteHppeGFzLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyOWVlNTE2Ni1kMTFjLTQ5NjItYjc5MC0zMzkyZGZlNGI5ZDgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUxODUwNzkwLCJpYXQiOjE3NTE4NDcxOTAsImVtYWlsIjoibGVrYW5tb2ppYm9sYUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MTg0NzE5MH1dLCJzZXNzaW9uX2lkIjoiYjhlMjI2NDUtZTcwZi00ODZiLTk1MTUtNmNkZjJiMTc4MjdhIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.swTCltaqscEp-NUqSIz3bhkJEwd5lkloB9bSnHlmdCM"
}