### Variables
@baseUrl = http://localhost:8080/auth
@contentType = application/json

### 1. Register a Vendor (Username is MANDATORY)
# @name verifyVendor
POST {{baseUrl}}/verify-otp
Content-Type: {{contentType}}

{
    "email": "dulcea8@sharebot.net",
    "otp": "827351"
}